import { Inter } from 'next/font/google'
import './globals.css'
import { getServerSession } from 'next-auth'
import SessionProvider from '@/utils/SessionProvider'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sila Marketing Agency',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang='en'>
      <head>
        <link rel='icon' href='/images/logoCommission.png' />
      </head>
      <body className={inter.className}>
        <SessionProvider session={session}>{children}</SessionProvider>
      </body>
    </html>
  )
}
